-- ============================================================
-- Trust & Safety Risk Analytics — Exploratory SQL
-- Business questions a Product/Strategy Analyst would be asked
-- ============================================================

-- Q1. How is content split between claims and opinions, and does that
--     split differ by author ban status?
SELECT
    author_ban_status,
    claim_status,
    COUNT(*)                                              AS n_videos,
    ROUND(100.0 * COUNT(*) / SUM(COUNT(*)) OVER (
        PARTITION BY author_ban_status), 1)               AS pct_within_ban_status
FROM videos
GROUP BY author_ban_status, claim_status
ORDER BY author_ban_status, claim_status;


-- Q2. Do banned / under-review authors show a different engagement
--     "shape" than active authors? (avg views, likes, shares, comments)
SELECT
    author_ban_status,
    COUNT(*)                               AS n_videos,
    ROUND(AVG(video_view_count), 0)        AS avg_views,
    ROUND(AVG(video_like_count), 0)        AS avg_likes,
    ROUND(AVG(video_share_count), 0)       AS avg_shares,
    ROUND(AVG(video_comment_count), 0)     AS avg_comments,
    ROUND(AVG(video_download_count), 0)    AS avg_downloads
FROM videos
GROUP BY author_ban_status
ORDER BY avg_views DESC;


-- Q3. Engagement RATIOS matter more than raw counts (a bot-boosted video
--     can have high views with an abnormal share-to-view ratio). Compute
--     share-rate and comment-rate per ban status.
SELECT
    author_ban_status,
    ROUND(AVG(1.0 * video_share_count / NULLIF(video_view_count, 0)), 4)   AS avg_share_rate,
    ROUND(AVG(1.0 * video_comment_count / NULLIF(video_view_count, 0)), 4) AS avg_comment_rate,
    ROUND(AVG(1.0 * video_like_count / NULLIF(video_view_count, 0)), 4)    AS avg_like_rate
FROM videos
GROUP BY author_ban_status
ORDER BY avg_share_rate DESC;


-- Q4. Is claim-type content disproportionately produced by banned /
--     under-review authors? (the "claim risk" hypothesis)
SELECT
    claim_status,
    COUNT(*)                                                        AS n_videos,
    SUM(CASE WHEN author_ban_status = 'banned' THEN 1 ELSE 0 END)   AS n_banned,
    ROUND(100.0 * SUM(CASE WHEN author_ban_status = 'banned' THEN 1 ELSE 0 END)
        / COUNT(*), 2)                                              AS pct_banned,
    ROUND(100.0 * SUM(CASE WHEN author_ban_status = 'under review' THEN 1 ELSE 0 END)
        / COUNT(*), 2)                                              AS pct_under_review
FROM videos
GROUP BY claim_status;


-- Q5. Verified accounts vs ban status — does verification correlate with
--     lower risk? (basic trust-signal check)
SELECT
    verified_status,
    author_ban_status,
    COUNT(*) AS n_videos,
    ROUND(100.0 * COUNT(*) / SUM(COUNT(*)) OVER (PARTITION BY verified_status), 1) AS pct
FROM videos
GROUP BY verified_status, author_ban_status
ORDER BY verified_status, author_ban_status;


-- Q6. Video duration distribution by ban status — do risky authors post
--     systematically shorter/longer videos?
SELECT
    author_ban_status,
    ROUND(AVG(video_duration_sec), 1) AS avg_duration_sec,
    MIN(video_duration_sec)           AS min_duration,
    MAX(video_duration_sec)           AS max_duration
FROM videos
GROUP BY author_ban_status;


-- Q7. Rank the top 1% most-viewed videos and check their ban-status mix
--     (does virality cluster among risky accounts?) — uses a window
--     function (NTILE) rather than a hardcoded threshold.
WITH ranked AS (
    SELECT
        *,
        NTILE(100) OVER (ORDER BY video_view_count DESC) AS view_percentile
    FROM videos
)
SELECT
    author_ban_status,
    COUNT(*) AS n_in_top_1pct
FROM ranked
WHERE view_percentile = 1
GROUP BY author_ban_status
ORDER BY n_in_top_1pct DESC;


-- Q8. "At-risk share of engagement" — what % of total platform views /
--     shares are generated by banned + under-review authors? This is the
--     single number a founder/PM would actually want in a deck.
WITH totals AS (
    SELECT
        SUM(video_view_count)  AS total_views,
        SUM(video_share_count) AS total_shares
    FROM videos
)
SELECT
    ROUND(100.0 * SUM(CASE WHEN v.author_ban_status IN ('banned','under review')
        THEN v.video_view_count ELSE 0 END) / t.total_views, 2)  AS pct_views_from_at_risk,
    ROUND(100.0 * SUM(CASE WHEN v.author_ban_status IN ('banned','under review')
        THEN v.video_share_count ELSE 0 END) / t.total_shares, 2) AS pct_shares_from_at_risk
FROM videos v
CROSS JOIN totals t;
